---
"trigger.dev": patch
---

TriggerApiError 4xx errors will no longer cause tasks to be retried
